### ISSUE TITLE
Errors on build

### ISSUE THREAD

**Issue by bertung** [plasma-umass/doppio#421]
I made a clean git, and "grunt release" gives the following errors.

/Users/bora/Development/DoppioJVM/doppio/console/doppioh.ts(23,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/console/doppioh.ts(24,26): error TS2307: Cannot find module '../vendor/java_home/jdk.json'.
/Users/bora/Development/DoppioJVM/doppio/console/doppioh.ts(650,45): error TS7006: Parameter 'item' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/console/find_invalid_natives.ts(14,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/console/find_invalid_natives.ts(16,26): error TS2307: Cannot find module '../vendor/java_home/jdk.json'.
/Users/bora/Development/DoppioJVM/doppio/console/runner.ts(7,26): error TS2307: Cannot find module '../vendor/java_home/jdk.json'.
/Users/bora/Development/DoppioJVM/doppio/console/test_runner.ts(6,26): error TS2307: Cannot find module '../vendor/java_home/jdk.json'.
/Users/bora/Development/DoppioJVM/doppio/src/ClassData.ts(16,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/ClassLoader.ts(13,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/ConstantPool.ts(12,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/jvm.ts(15,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/jvm.ts(19,26): error TS2307: Cannot find module '../vendor/java_home/jdk.json'.
/Users/bora/Development/DoppioJVM/doppio/src/jvm.ts(277,50): error TS7006: Parameter 'item' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/src/methods.ts(15,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/classes_doppio.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_io.ts(11,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_lang.ts(18,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_lang.ts(122,143): error TS7006: Parameter 'iface' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_lang.ts(279,31): error TS7006: Parameter 'f' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_lang.ts(773,36): error TS7006: Parameter 'cls' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_net.ts(10,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_nio.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_security.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/java_util.ts(2,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_font.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_management.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_misc.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_net.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_nio.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_nio.ts(214,97): error TS7006: Parameter 'e' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_nio.ts(222,97): error TS7006: Parameter 'e' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/src/natives/sun_reflect.ts(1,27): error TS2307: Cannot find module '../../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/opcodes.ts(18,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/threading.ts(13,27): error TS2307: Cannot find module '../includes/JVMTypes'.
/Users/bora/Development/DoppioJVM/doppio/src/threading.ts(825,55): error TS7006: Parameter 'e' implicitly has an 'any' type.
/Users/bora/Development/DoppioJVM/doppio/src/util.ts(5,27): error TS2307: Cannot find module '../includes/JVMTypes'.

>> 36 non-emit-preventing type warnings  
>> Type errors only.

TypeScript compilation complete: 21.59s for 54 TypeScript files.

Running "check_jdk" task
Warning: Task "check_jdk" failed. Use --force to continue.

**Comment by kennycoc** [comment]
I'm getting the same error. check_jdk keeps failing

**Comment by kennycoc** [comment]
yeah, me too. I've tried checking out previous commits, but I still get the same error. It must be something unique to our build environments. @bertung, are you using Windows 10?

**Comment by jvilk** [comment]
On my way home to look at this. I need to re add doppios dependence on rimraf. That is most likely the culprit.

**Comment by kennycoc** [comment]
Adding rimraf as a dependency fixed it the initial problem, but now I'm getting an error after 
"Running 
"javac:default" (javac) task" 

[log.txt](https://github.com/plasma-umass/doppio/files/101624/log.txt)

**Comment by kennycoc** [comment]
Also, I have to run "tsc" before "npm install" is this expected? Should we update the documentation?

**Comment by jvilk** [comment]
You shouldn't have to do that, @kennycoc. `npm install` should "just work" out of the box.

```
$ git clone https://github.com/plasma-umass/doppio doppio-test-clean
Cloning into 'doppio-test-clean'...
remote: Counting objects: 63281, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 63281 (delta 0), reused 0 (delta 0), pack-reused 63278
Receiving objects: 100% (63281/63281), 74.83 MiB | 9.06 MiB/s, done.
Resolving deltas: 100% (25187/25187), done.
Checking connectivity... done.
$ cd doppio-test-clean/
$ npm install
<lots of output, which filled my terminal's buffer :) >
$ ./doppio
Usage: /usr/local/bin/node build/release-cli/console/runner.js [-options] class [args...]
        (to execute a class)
or  /usr/local/bin/node build/release-cli/console/runner.js [-options] -jar jarfile [args...]
        (to execute a jar file)
where options include:
    -classpath <class search path of directories and zip/jar files>
    -cp <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives, and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -help | -?    print this help message
    -X            print help on non-standard options
    -enableassertions[:<packagename>...|:<classname>]
    -ea[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -disableassertions[:<packagename>...|:<classname>]
    -da[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -enablesystemassertions | -esa
                  enable system assertions
    -disablesystemassertions | -dsa
                  disable system assertions
```

I committed the `rimraf` change, btw.

**Comment by jvilk** [comment]
@kennycoc the issue is your Java installation's default character encoding. We expect UTF-8. I'm going to push a change soon to force UTF-8 during compilation and during runtime with a flag to `java` and `javac`.

**Comment by jvilk** [comment]
@kennycoc let me know if that fixes your issue. Also, if a clean clone+build still fails, I'd like to know about it. :)

**Comment by kennycoc** [comment]
Okay! One second

**Comment by kennycoc** [comment]
Yeah, I'm still getting the same errors :(

...
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './Grunttasks'
Warning: Task "dist" not found. Use --force to continue.

Aborted due to warnings.
C:\Users\kenne\upwork\doppio\prepublish.js:13
    throw new Error("Program exited with code " + code);
    ^
...

**Comment by kennycoc** [comment]
If I run tsc, and then npm install, I get all the way past downloading the new JDK, but then it still crashes at "running javac:default (javac) task"

**Comment by jvilk** [comment]
@kennycoc I just pushed a change that should fix the `tsc` issue in Windows (I forgot to include code that looked for `node_modules/.bin/tsc.cmd` instead of `node_modules/.bin/tsc` on Windows).

What's the current `javac` error? Is it the same after the last push I did?

**Comment by kennycoc** [comment]
I get 
```

Running "javac:default" (javac) task
Fatal error: Error running javac: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\PROGRA~1\Java\JDK18~1.0_7\bin\javac.exe -J-Dfile.encoding=UTF8 -bootclasspath C:\Users\kenne\upwork\doppio\vendor\java_home\lib\rt.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\charsets.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\doppio.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\dt.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\jce.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\jconsole.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\jsse.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\management-agent.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\resources.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\sa-jdi.jar:C:\Users\kenne\upwork\doppio\vendor\java_home\lib\tools.jar -source 1.8 -target 1.8 classes/awt/CanvasGraphicsEnvironment.java classes/demo/AsciiArt.java classes/demo/Chatterbot.java classes/demo/Diff.java classes/demo/DiffPrint.java classes/demo/Fib.java classes/demo/GzipDemo.java classes/demo/RegexTestHarness.java classes/doppio/Debug.java classes/doppio/JavaScript.java classes/test/Annotations.java classes/test/ArrayCopyTest.java classes/test/ArrayListOps.java classes/test/ArrayOps.java classes/test/AssertionTest.java classes/test/ByteBufferTest.java classes/test/ByteParse.java classes/test/Casting.java classes/test/CatchingClinitException.java classes/test/Checksums.java classes/test/ClassCast.java classes/test/Clinit.java classes/test/Clone.java classes/test/Compare.java classes/test/ConcatStrings.java classes/test/ConcurrentClinit.java classes/test/CustomClassLoader.java classes/test/CustomClassLoader2.java classes/test/DefaultInterfaceMethodTest.java classes/test/DoubleMath.java classes/test/Dup.java classes/test/Exceptional.java classes/test/FileDescriptors.java classes/test/FileHandle.java classes/test/FileOps.java classes/test/FileRead.java classes/test/FileWrite.java classes/test/FloatMath.java classes/test/GCD.java classes/test/GenericSignature.java classes/test/GetClass.java classes/test/HashCode.java classes/test/HashMapOps.java classes/test/Inheritance.java classes/test/InnerClass.java classes/test/IntMath.java classes/test/Interfaces.java classes/test/LongMath.java classes/test/MesaTest.java classes/test/NashornTest.java classes/test/NegativeArrays.java classes/test/NioFilesPaths.java classes/test/Numbers.java classes/test/OMember.java classes/test/OMethod.java classes/test/PackageTest.java classes/test/ParkUnpark.java classes/test/RAFile.java classes/test/RawMemory.java classes/test/Reflection.java classes/test/Regex.java classes/test/Runtime.java classes/test/ScannerTest.java classes/test/Serialization.java classes/test/SignaturePolymorphicTest.java classes/test/SlotTest.java classes/test/StaticField.java classes/test/StaticMethod.java classes/test/StreamTest.java classes/test/StrictMathTest.java classes/test/StringInternExample.java classes/test/Strings.java classes/test/Switch.java classes/test/Synchronized.java classes/test/SynchronizedStart.java classes/test/ThreadFromClinit.java classes/test/Threading.java classes/test/UTFTest.java classes/test/UnsafeOps.java classes/test/WaitTest.java classes/test/Wide.java classes/util/FindJclClasses.java classes/util/Javac.java classes/util/Javap.java classes/util/SystemProperties.java classes/util/Unzip.java"
Fatal Error: Unable to find package java.lang in classpath or bootclasspath

C:\Users\kenne\upwork\doppio\prepublish.js:13
    throw new Error("Program exited with code " + code);
    ^
```

I'll pull the changes and try again

**Comment by kennycoc** [comment]
Alright, that fixed most of it! Now I get 
```

Running "includes:default" (includes) task
Fatal error: Could not run doppioh (exit code 1): Error:
../../../console/doppioh.ts:130
    throw new Error(`Unable to find resource ${item}.`);
          ^
Error: Unable to find resource classes/doppio.
    at getClasses (../../../console/doppioh.ts:130:11)
    at ../../../console/doppioh.ts:682:21
    at Array.forEach (native)
    at ../../../console/doppioh.ts:676:16
    at C:\Users\kenne\upwork\doppio\node_modules\async\lib\async.js:52:16
    at done (C:\Users\kenne\upwork\doppio\node_modules\async\lib\async.js:246:17)
    at C:\Users\kenne\upwork\doppio\node_modules\async\lib\async.js:44:16
    at ../../../src/classpath.ts:95:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)


../../../console/doppioh.ts:130
    throw new Error(`Unable to find resource ${item}.`);
          ^
Error: Unable to find resource classes/doppio.
    at getClasses (../../../console/doppioh.ts:130:11)
    at ../../../console/doppioh.ts:682:21
    at Array.forEach (native)
    at ../../../console/doppioh.ts:676:16
    at C:\Users\kenne\upwork\doppio\node_modules\async\lib\async.js:52:16
    at done (C:\Users\kenne\upwork\doppio\node_modules\async\lib\async.js:246:17)
    at C:\Users\kenne\upwork\doppio\node_modules\async\lib\async.js:44:16
    at ../../../src/classpath.ts:95:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
C:\Users\kenne\upwork\doppio\prepublish.js:13
    throw new Error("Program exited with code " + code);
    ^
```

**Comment by jvilk** [comment]
I'm booting up a Windows VM to see if I can reproduce this.

**Comment by jvilk** [comment]
Reproduced! Working on it now.

**Comment by kennycoc** [comment]
But sometimes it also crashes on the other one. It's always either at javac, or includes.

**Comment by jvilk** [comment]
I just fixed the Java and Javac tasks. Includes is still broken. Looking into it...

**Comment by jvilk** [comment]
Includes is fixed. DoppioJVM now *builds* on Windows, but it does not *run*. Looks like classloading is broken in Windows due to the different path separators (`\` instead of `/`). Ugh.

I'll open a task for fixing DoppioJVM on Windows to look at tomorrow.

**Comment by kennycoc** [comment]
Which files are relevant to this? I can work on it if it would be helpful

**Comment by jvilk** [comment]
@kennycoc `src/classpath.ts` is likely relevant. After building DoppioJVM, you can see that it fails to run anything you pass to it, e.g.:

```
doppio.bat classes.test.AnnotationTest
```

...will fail with a class not found error.

**Comment by bertung** [comment]
It works fine on MacOS now. Thank you.
